#!/bin/bash

# See https://docs.openshift.org/latest/creating_images/custom.html#custom-builder-image
# for the list of environment variables set by OpenShift before the custom
# builder image is run.
#
# Although set as part of the API, the environment variables
# SOURCE_REPOSITORY/SOURCE_URI, SOURCE_CONTEXT_DIR and SOURCE_REF can also be
# derived from the BUILD environment variable using a tool such as `jq`
# (https://stedolan.github.io/jq/).  (Note: you would need to include the `jq`
# binary in your custom builder image).  If necessary, this technique can be
# used for extracting other values from the BUILD json from a shell script.
#
# SOURCE_REPOSITORY=$(jq -nr '(env.BUILD|fromjson).spec.source.git.uri')
# SOURCE_URI=$(jq -nr '(env.BUILD|fromjson).spec.source.git.uri')
# SOURCE_CONTEXT_DIR=$(jq -nr '(env.BUILD|fromjson).spec.source.contextDir')
# SOURCE_REF=$(jq -nr '(env.BUILD|fromjson).spec.source.git.ref')

set -o pipefail
IFS=$'\n\t'

IMAGE_NAME=${IMAGE_NAME-arnaudeprez/jenkins-openshift:latest}
DOCKER_SOCKET=/var/run/docker.sock

if [ ! -e "${DOCKER_SOCKET}" ]; then
  echo "Docker socket missing at ${DOCKER_SOCKET}"
  exit 1
fi

# More info here: https://www.testcontainers.org/usage/inside_docker.html
MAVEN_PROJECT_DIR="$PWD/test/integration-tests"
echo "Execute tests of in $MAVEN_PROJECT_DIR"
docker run --rm -ti -v $MAVEN_PROJECT_DIR:/usr/src/integration-tests -v $DOCKER_SOCKET:$DOCKER_SOCKET -w /usr/src/integration-tests --user root maven:3-jdk-8-alpine mvn -e test -Dimage.name=$IMAGE_NAME