{{- if and .Values.Master.HostName (eq "openshift" .Values.Deployment.Type) -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{ include "jenkins-openshift.labels" . | nindent 4 | trim }}
  annotations:
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    {{- if .Values.Master.Ingress.Annotations }}
    {{ toYaml .Values.Master.Ingress.Annotations | nindent 4 | trim}}
    {{- end }}
  name: {{ template "jenkins-openshift.fullname" . }}
spec:
  host: {{ .Values.Master.HostName }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ template "jenkins-openshift.fullname" . }}
{{- end }}