{{- if and (.Values.Master.HostName) (not (eq "openshift" .Values.Deployment.Type)) -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    {{ include "jenkins-openshift.labels" . | nindent 4 | trim }}
  annotations:
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    {{- if .Values.Master.Ingress.Annotations }}
    {{ toYaml .Values.Master.Ingress.Annotations | nindent 4 | trim }}
    {{- end }}
  name: {{ template "jenkins-openshift.fullname" . }}
spec:
  rules:
  - host: {{ .Values.Master.HostName | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ template "jenkins-openshift.fullname" . }}
          servicePort: {{ .Values.Master.ServicePort }}
  {{- if .Values.Master.Ingress.TLS }}
  tls:
    {{ toYaml .Values.Master.Ingress.TLS | nindent 4 | trim }}
  {{- end }}
{{- end }}