apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins-openshift.fullname" . }}-agent
  labels:
    {{ include "jenkins-openshift.labels" . | nindent 4 | trim }}
  {{- if .Values.Master.SlaveListenerServiceAnnotations }}
  annotations:
    {{ toYaml .Values.Master.SlaveListenerServiceAnnotations | nindent 4 | trim }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.Master.AgentListenerPort }}
      targetPort: {{ .Values.Master.AgentListenerPort }}
      name: slavelistener
  selector:
    app.kubernetes.io/name: {{ include "jenkins-openshift.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.Master.SlaveListenerServiceType }}