FROM arnaudeprez/jenkins-agent-base:latest

LABEL maintainer="Arnaud Deprez <arnaudeprez@gmail.com>"

ENV GRADLE_HOME=/opt/gradle

ARG GRADLE_VERSION=5.2.1
ARG GRADLE_DOWNLOAD_SHA256=748c33ff8d216736723be4037085b8dc342c6a0f309081acf682c9803e407357

USER root

RUN yum-config-manager --enable "rhel-7-server-rpms" \
    && INSTALL_PKGS="java-11-openjdk-devel.x86_64 java-11-openjdk-devel.i686" \
    && yum install -y $INSTALL_PKGS \
	&& echo "Downloading Gradle" \
	&& curl -fsSL -o gradle.zip "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" \
	\
	&& echo "Checking download hash" \
	&& echo "${GRADLE_DOWNLOAD_SHA256} *gradle.zip" | sha256sum -c - \
	\
	&& echo "Installing Gradle" \
	&& unzip gradle.zip \
	&& rm gradle.zip \
	&& mkdir -p /opt \
	&& mv "gradle-${GRADLE_VERSION}" "${GRADLE_HOME}/" \
    && ln --symbolic "${GRADLE_HOME}/bin/gradle" /usr/bin/gradle \
    && mkdir -p $HOME/.gradle \
    && rpm -V $INSTALL_PKGS \
    && yum clean all -y \
	&& rm -rf /var/cache/yum/*

ADD gradle/ $GRADLE_HOME/
ADD test $HOME/test

RUN chown -R 1001:0 $HOME && \
    chmod -R g+rw $HOME

USER 1001
