FROM registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.10

COPY plugins.txt /opt/openshift/configuration/plugins.txt

# Remove example job and install plugins
RUN rm -rf /opt/openshift/configuration/jobs && \
    /usr/local/bin/install-plugins.sh /opt/openshift/configuration/plugins.txt
