FROM registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.10

COPY plugins.txt /opt/openshift/configuration/plugins.txt
RUN /usr/local/bin/install-plugins.sh /opt/openshift/configuration/plugins.txt
